services:
  roue-chance:
    build:
      context: .
      dockerfile: Dockerfile
    image: roue-chance:latest
    container_name: MaRoue
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
    volumes:
      - roue-data:/app/data

volumes:
  roue-data:
